# dbs:
#  - path: /path/to/primary/db            # Database to replicate from
#    replicas:
#      - path: /path/to/replica           # File-based replication
#      - url:  s3://my.bucket.com/db      # S3-based replication